# Generated by Django 4.2.5 on 2023-10-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('IRE', 'Ireland'), ('UK', 'United Kingdom'), ('US', 'United States'), ('BR', 'Brazil')], max_length=200)),
                ('city', models.CharField(choices=[('London', 'London'), ('New York', 'New York'), ('Sao Paulo', 'Sao Paulo'), ('Dublin', 'Dublin')], max_length=200)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Green', 'Green'), ('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow')], max_length=200)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('body_type', models.CharField(choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Van', 'Van'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV')], max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('engine', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Petrol', 'Petrol'), ('Gas', 'Gas')], max_length=200)),
                ('engine_size', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(choices=[('Auto Start/Stop', 'Auto Start/Stop'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Cruise Control', 'Cruise Control'), ('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Power Steering', 'Power Steering'), ('Airbags', 'Airbags'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Reversing Camera', 'Reversing Camera'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Audio Interface', 'Audio Interface')], default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
