# Generated by Django 4.2.5 on 2023-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='featured',
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Convertible', 'Convertible'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Van', 'Van'), ('Hatchback', 'Hatchback')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('New York', 'New York'), ('London', 'London'), ('Sao Paulo', 'Sao Paulo')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('White', 'White'), ('Green', 'Green'), ('Blue', 'Blue')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('IRE', 'Ireland'), ('UK', 'United Kingdom'), ('BR', 'Brazil')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Gas', 'Gas'), ('Hybrid', 'Hybrid'), ('Petrol', 'Petrol')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=200),
        ),
    ]
