# Generated by Django 4.2.5 on 2023-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_featured_alter_car_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Airbags', 'Airbags'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Cruise Control', 'Cruise Control'), ('Air Conditioning', 'Air Conditioning'), ('Auto Start/Stop', 'Auto Start/Stop'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera')], max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Airbags', 'Airbags'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Cruise Control', 'Cruise Control'), ('Air Conditioning', 'Air Conditioning'), ('Auto Start/Stop', 'Auto Start/Stop'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera')], max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Airbags', 'Airbags'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Cruise Control', 'Cruise Control'), ('Air Conditioning', 'Air Conditioning'), ('Auto Start/Stop', 'Auto Start/Stop'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Van', 'Van'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('Sao Paulo', 'Sao Paulo'), ('New York', 'New York'), ('Dublin', 'Dublin')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Grey', 'Grey'), ('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('BR', 'Brazil'), ('UK', 'United Kingdom'), ('IRE', 'Ireland')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Electric', 'Electric'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200),
        ),
    ]
