# Generated by Django 4.2.5 on 2023-10-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_feature1_car_feature2_car_feature3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Van', 'Van'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('London', 'London'), ('New York', 'New York'), ('Sao Paulo', 'Sao Paulo')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Grey', 'Grey'), ('Red', 'Red'), ('Green', 'Green')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('IRE', 'Ireland'), ('BR', 'Brazil'), ('UK', 'United Kingdom')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Gas', 'Gas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Reversing Camera', 'Reversing Camera'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Power Steering', 'Power Steering'), ('Wind Deflector', 'Wind Deflector'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Reversing Camera', 'Reversing Camera'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Power Steering', 'Power Steering'), ('Wind Deflector', 'Wind Deflector'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Reversing Camera', 'Reversing Camera'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Power Steering', 'Power Steering'), ('Wind Deflector', 'Wind Deflector'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating')], max_length=200),
        ),
    ]
