# Generated by Django 4.2.5 on 2023-10-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Van', 'Van'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Sao Paulo', 'Sao Paulo'), ('Dublin', 'Dublin'), ('New York', 'New York'), ('London', 'London')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States'), ('IRE', 'Ireland'), ('UK', 'United Kingdom')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Gas', 'Gas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'), ('Cruise Control', 'Cruise Control'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'), ('Cruise Control', 'Cruise Control'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'), ('Cruise Control', 'Cruise Control'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=200),
        ),
    ]
