# Generated by Django 4.2.5 on 2023-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Van', 'Van'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Sedan', 'Sedan')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('Dublin', 'Dublin'), ('New York', 'New York'), ('Sao Paulo', 'Sao Paulo')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Grey', 'Grey'), ('White', 'White'), ('Green', 'Green')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('IRE', 'Ireland'), ('BR', 'Brazil'), ('US', 'United States')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Audio Interface', 'Audio Interface'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Alarm System', 'Alarm System'), ('Power Steering', 'Power Steering'), ('Air Conditioning', 'Air Conditioning'), ('Wind Deflector', 'Wind Deflector')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Audio Interface', 'Audio Interface'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Alarm System', 'Alarm System'), ('Power Steering', 'Power Steering'), ('Air Conditioning', 'Air Conditioning'), ('Wind Deflector', 'Wind Deflector')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Audio Interface', 'Audio Interface'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('ParkAssist', 'ParkAssist'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Alarm System', 'Alarm System'), ('Power Steering', 'Power Steering'), ('Air Conditioning', 'Air Conditioning'), ('Wind Deflector', 'Wind Deflector')], max_length=200),
        ),
    ]
