# Generated by Django 4.2.5 on 2023-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Van', 'Van'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Sao Paulo', 'Sao Paulo'), ('New York', 'New York'), ('London', 'London'), ('Dublin', 'Dublin')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('White', 'White'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('Grey', 'Grey')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('IRE', 'Ireland'), ('US', 'United States'), ('UK', 'United Kingdom'), ('BR', 'Brazil')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Petrol', 'Petrol'), ('Gas', 'Gas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Air Conditioning', 'Air Conditioning'), ('Power Steering', 'Power Steering'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Direct Fuel Injection', 'Direct Fuel Injection')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Air Conditioning', 'Air Conditioning'), ('Power Steering', 'Power Steering'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Direct Fuel Injection', 'Direct Fuel Injection')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Air Conditioning', 'Air Conditioning'), ('Power Steering', 'Power Steering'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Direct Fuel Injection', 'Direct Fuel Injection')], max_length=200),
        ),
    ]
