# Generated by Django 4.2.5 on 2023-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Van', 'Van'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Sao Paulo', 'Sao Paulo'), ('Dublin', 'Dublin'), ('London', 'London'), ('New York', 'New York')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Grey', 'Grey'), ('Blue', 'Blue')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('IRE', 'Ireland'), ('BR', 'Brazil'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Gas', 'Gas'), ('Electric', 'Electric')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Audio Interface', 'Audio Interface'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Cruise Control', 'Cruise Control'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('Seat Heating', 'Seat Heating')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Audio Interface', 'Audio Interface'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Cruise Control', 'Cruise Control'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('Seat Heating', 'Seat Heating')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Audio Interface', 'Audio Interface'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Cruise Control', 'Cruise Control'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('Seat Heating', 'Seat Heating')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200),
        ),
    ]
