# Generated by Django 4.2.5 on 2023-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Convertible', 'Convertible'), ('Van', 'Van'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('New York', 'New York'), ('London', 'London'), ('Sao Paulo', 'Sao Paulo'), ('Dublin', 'Dublin')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Green', 'Green'), ('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('IRE', 'Ireland'), ('BR', 'Brazil'), ('US', 'United States')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Gas', 'Gas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Power Steering', 'Power Steering'), ('Audio Interface', 'Audio Interface'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Cruise Control', 'Cruise Control')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Power Steering', 'Power Steering'), ('Audio Interface', 'Audio Interface'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Cruise Control', 'Cruise Control')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Power Steering', 'Power Steering'), ('Audio Interface', 'Audio Interface'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Airbags', 'Airbags'), ('Wind Deflector', 'Wind Deflector'), ('Cruise Control', 'Cruise Control')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=200),
        ),
    ]
