# Generated by Django 4.2.5 on 2023-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('New York', 'New York'), ('Sao Paulo', 'Sao Paulo'), ('Dublin', 'Dublin'), ('London', 'London')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White'), ('Red', 'Red')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('IRE', 'Ireland'), ('BR', 'Brazil'), ('US', 'United States'), ('UK', 'United Kingdom')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Diesel', 'Diesel'), ('Gas', 'Gas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Wind Deflector', 'Wind Deflector'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Airbags', 'Airbags'), ('Cruise Control', 'Cruise Control'), ('Seat Heating', 'Seat Heating'), ('Air Conditioning', 'Air Conditioning'), ('Reversing Camera', 'Reversing Camera'), ('Power Steering', 'Power Steering'), ('ParkAssist', 'ParkAssist')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Wind Deflector', 'Wind Deflector'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Airbags', 'Airbags'), ('Cruise Control', 'Cruise Control'), ('Seat Heating', 'Seat Heating'), ('Air Conditioning', 'Air Conditioning'), ('Reversing Camera', 'Reversing Camera'), ('Power Steering', 'Power Steering'), ('ParkAssist', 'ParkAssist')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Wind Deflector', 'Wind Deflector'), ('Audio Interface', 'Audio Interface'), ('Alarm System', 'Alarm System'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Airbags', 'Airbags'), ('Cruise Control', 'Cruise Control'), ('Seat Heating', 'Seat Heating'), ('Air Conditioning', 'Air Conditioning'), ('Reversing Camera', 'Reversing Camera'), ('Power Steering', 'Power Steering'), ('ParkAssist', 'ParkAssist')], max_length=200),
        ),
    ]
