# Generated by Django 4.2.5 on 2023-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Sao Paulo', 'Sao Paulo'), ('London', 'London'), ('Dublin', 'Dublin'), ('New York', 'New York')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Grey', 'Grey'), ('White', 'White')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('UK', 'United Kingdom'), ('IRE', 'Ireland'), ('US', 'United States')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Gas', 'Gas'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Diesel', 'Diesel')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Seat Heating', 'Seat Heating'), ('Audio Interface', 'Audio Interface'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Alarm System', 'Alarm System')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Seat Heating', 'Seat Heating'), ('Audio Interface', 'Audio Interface'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Alarm System', 'Alarm System')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Seat Heating', 'Seat Heating'), ('Audio Interface', 'Audio Interface'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Alarm System', 'Alarm System')], max_length=200),
        ),
    ]
