# Generated by Django 4.2.5 on 2023-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Van', 'Van'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('London', 'London'), ('Sao Paulo', 'Sao Paulo'), ('New York', 'New York')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Green', 'Green'), ('White', 'White')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States'), ('UK', 'United Kingdom'), ('IRE', 'Ireland')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('Audio Interface', 'Audio Interface'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Cruise Control', 'Cruise Control'), ('Bluetooth Handset', 'Bluetooth Handset'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Airbags', 'Airbags')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('Audio Interface', 'Audio Interface'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Cruise Control', 'Cruise Control'), ('Bluetooth Handset', 'Bluetooth Handset'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Airbags', 'Airbags')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('Audio Interface', 'Audio Interface'), ('Seat Heating', 'Seat Heating'), ('Reversing Camera', 'Reversing Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Cruise Control', 'Cruise Control'), ('Bluetooth Handset', 'Bluetooth Handset'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Airbags', 'Airbags')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200),
        ),
    ]
