# Generated by Django 4.2.5 on 2023-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_body_type_alter_car_city_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Van', 'Van'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('Hatchback', 'Hatchback')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Sao Paulo', 'Sao Paulo'), ('New York', 'New York'), ('London', 'London'), ('Dublin', 'Dublin')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Grey', 'Grey'), ('Green', 'Green')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('IRE', 'Ireland'), ('US', 'United States'), ('UK', 'United Kingdom')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Petrol', 'Petrol')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature1',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Seat Heating', 'Seat Heating'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Wind Deflector', 'Wind Deflector')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature2',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Seat Heating', 'Seat Heating'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Wind Deflector', 'Wind Deflector')], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='feature3',
            field=models.CharField(blank=True, choices=[('Alarm System', 'Alarm System'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Seat Heating', 'Seat Heating'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Wind Deflector', 'Wind Deflector')], max_length=200),
        ),
    ]
